---
# handlers file for deploy_ELK
#- name: restart_ELK
#  service:
#    name: "{{ item }}"
#    state: restarted
#    enabled: yes
#    use: service
#  loop: "{{ ELK }}"
- name: restart_elasticsearch
  shell:  systemctl restart elasticsearch.service
- name: restart_kibana
  shell: systemctl restart kibana.service
- name: restart_logstash
  shell: systemctl restart logstash.service

- name: persist_elk
  shell: |
    - systemctl enable elasticsearch
    - systemctl enable kibana
    - systemctl enable logstash
