---

##### Metricbeat

 name: Configruring metricbeat.yml {output.elasticsearch}
  lineinfile:
       path: /etc/metricbeat/metricbeat.yml 
       regex: "  #protocol:"
       line: '  protocol: "https"'
 

- name: Provide input to create keystore
  command: echo "y" | metricbeat keystore create
- name: Add metricbeat entry ES_UN
  expect:
        command: metricbeat keystore add ES_UN
        responses:
          "Enter value for ES_UN: ": "elastic\n"

- name: Add keystore entry ES_PW
  expect:
        command: metricbeat keystore add ES_PW
        responses:
          "Enter value for ES_PW: ": "{{ elastic_pw_val.content | b64decode }}\n"     

- name: Adding elastic user credentials username
  lineinfile:
      path: /etc/metricbeat/metricbeat.yml 
      regex: '  #username: "elastic"'
      line: "  username: ${ES_UN}"
- name: Adding elastic user credentials password
  lineinfile:
      path: /etc/metricbeat/metricbeat.yml 
      regex: '  #password: "changeme"'
      line: "  password: ${ES_PW}"

- name: Configuring metricbeat.yml { output.elasticsearch }  ca_trusted
  blockinfile:
       path: /etc/metricbeat/metricbeat.yml 
       insertafter: '  #password: "changeme"'
       block: |2
           ssl:
             enabled: true
             ca_trusted_fingerprint: "{{ ca_fingerprint_value }}"
      
- name: restart metricbeat
  shell: systemctl restart metricbeat.service
