---
# tasks file for beats_m# Configuring beats 
- name: Enabling metricbeat and starting it
  shell: |
     apt install packetbeat
     systemctl enable filebeat.service
     systemctl start filebeat.service
     systemctl enable metricbeat.service
     systemctl start metricbeat.serviceanagement
     systemctl enable packetbeat.service
     systemctl start packetbeat.service
     
- name: retrieve the elastic_pw value
  slurp:
       src: /home/ubuntu/elastic_pw
  register: elastic_pw_val

- name: Fixing permission of config files of beats
  shell: |
    sudo chmod 644 /etc/metricbeat/metricbeat.yml
    sudo chmod 644 /etc/filebeat/filebeat.yml
    sudo chmod 644 /etc/packetbeat/packetbeat.yml

##### Filebeat
- name: enabling elasticsearch, Nginx, System modules
  shell: |
    filebeat modules enable elasticsearch
    filebeat modules enable nginx
    filebeat modules enable system

- name: Configuring filebeat.yml file {output.filebeat}
  lineinfile:
       path: /etc/filebeat/filebeat.yml 
       regex: "  reload.enabled: false"
       line: "  reload.enabled: true"

- name: retrieving elasticsearch CA fingerprint for ssl config in filebeat.yml
  shell: | 
      awk -F: '/ca_trusted_fingerprint/ { gsub(/[}\]]/, "", $11); gsub(/^[[:space:]]+|[[:space:]]+$/, "", $11); print $11 }' /etc/kibana/kibana.yml
  register: ca_trusted_fingerprint
  
- name: Extract ca_trusted_fingerprint value
  set_fact:
     ca_fingerprint_value: "{{ ca_trusted_fingerprint.stdout }}"

- name: Configuring filebeat.yml { output.elasticsearch }  ca_trusted
  blockinfile:
       path: /etc/filebeat/filebeat.yml 
       insertafter: '  #password: "changeme"'
       block: |2
           ssl:
             enabled: true
             ca_trusted_fingerprint: "{{ ca_fingerprint_value }}"

- name: Configruring filebeat.yml {output.elasticsearch}
  lineinfile:
       path: /etc/filebeat/filebeat.yml 
       regex: "  #protocol:"
       line: '  protocol: "https"'

- name: Provide input to create keystore
  expect:
        command: filebeat keystore create
        responses:
          "A keystore already exists, Overwrite? [y/N]: ": "y\n"
  ignore_errors: yes  # Ignore errors in case the keystore doesn't exist
      
- name: Add keystore entry ES_UN (secret)
  expect:
        command: filebeat keystore add ES_UN
        responses:
          "Enter value for ES_UN: ": "elastic\n"

- name: Add keystore entry ES_PW
  expect:
        command: filebeat keystore add ES_PW
        responses:
          "Enter value for ES_PW: ": "{{ elastic_pw_val.content | b64decode }}\n"     


- name: Adding elastic user credentials username
  lineinfile:
      path: /etc/filebeat/filebeat.yml 
      regex: '  #username: "elastic"'
      line: "  username: ${ES_UN}"
- name: Adding elastic user credentials password
  lineinfile:
      path: /etc/filebeat/filebeat.yml 
      regex: '  #password: "changeme"'
      line: "  password: ${ES_PW}"
      
    
- name: deploying elasticsearch module config file
  template:
    src: elasticsearch.j2
    dest: /etc/filebeat/modules.d/elasticsearch.yml

- name: deploying NGINX module config file
  template:
    src: nginx.j2
    dest: /etc/filebeat/modules.d/nginx.yml    

- name: deploying SYSTEM module config file { SYSLOG }
  template:
    src: system.yml.j2
    dest: /etc/filebeat/modules.d/system.yml

- name: taking action to setup filebeat modules
  shell: |
    filebeat setup -e
    filebeat setup -e --index-management
- name: restart filebeat
  shell: systemctl restart filebeat.service


##### Metricbeat

- name: Configruring metricbeat.yml {output.elasticsearch}
  lineinfile:
       path: /etc/metricbeat/metricbeat.yml 
       regex: "  #protocol:"
       line: '  protocol: "https"'

- name: Provide input to create keystore
  expect:
        command: metricbeat keystore create
        responses:
          "A keystore already exists, Overwrite? [y/N]: ": "y\n"
  ignore_errors: yes  # Ignore errors in case the keystore doesn't exis
  
- name: Add metricbeat entry ES_UN (secret)
  expect:
        command: metricbeat keystore add ES_UN
        responses:
          "The keystore does not exist. Do you want to create it? [y/N]: ": "y\n"
          "Enter value for ES_UN: ": "elastic\n"

- name: Add keystore entry ES_PW
  expect:
        command: metricbeat keystore add ES_PW
        responses:
          "Enter value for ES_PW: ": "{{ elastic_pw_val.content | b64decode }}\n"     

- name: Adding elastic user credentials username
  lineinfile:
      path: /etc/metricbeat/metricbeat.yml 
      regex: '  #username: "elastic"'
      line: "  username: ${ES_UN}"   
# This should be done before changing the value of #passowrd and removing #, its like an checkpoint getting removed, if it doesnt exist it will be appended in EOF
- name: Configuring metricbeat.yml { output.elasticsearch }  ca_trusted
  blockinfile:
       path: /etc/metricbeat/metricbeat.yml 
       insertafter: '  #password: "changeme"'
       block: |2
           ssl:
             enabled: true
             ca_trusted_fingerprint: "{{ ca_fingerprint_value }}"  
     
- name: Adding elastic user credentials password
  lineinfile:
      path: /etc/metricbeat/metricbeat.yml 
      regex: '  #password: "changeme"'
      line: "  password: ${ES_PW}"
 
- name: restart metricbeat
  shell: systemctl restart metricbeat.service

##### Packetbeat
- name: Ensuring libcap is installed
  apt:
     name: libpcap0.8
     state: latest
     
- name: Configruring packetbeat.yml {output.elasticsearch}
  lineinfile:
       path: /etc/packetbeat/packetbeat.yml 
       regex: "  #protocol:"
       line: '  protocol: "https"'

- name: Provide input to create keystore
  expect:
        command: packetbeat keystore create
        responses:
          "A keystore already exists, Overwrite? [y/N]: ": "y\n"
  ignore_errors: yes  # Ignore errors in case the keystore doesn't exis
  
- name: Add packetbeat entry ES_UN (secret)
  expect:
        command: packetbeat keystore add ES_UN
        responses:
          "The keystore does not exist. Do you want to create it? [y/N]: ": "y\n"
          "Enter value for ES_UN: ": "elastic\n" 

- name: Add keystore entry ES_PW
  expect:
        command: packetbeat keystore add ES_PW
        responses:
          "Enter value for ES_PW: ": "{{ elastic_pw_val.content | b64decode }}\n"     

- name: Adding elastic user credentials username
  lineinfile:
      path: /etc/packetbeat/packetbeat.yml 
      regex: '  #username: "elastic"'
      line: "  username: ${ES_UN}"
# This should be done before changing the value of #passowrd and removing #, its like an checkpoint getting removed, if it doesnt exist it will be appended in EOF
- name: Configuring packetbeat.yml { output.elasticsearch }  ca_trusted
  blockinfile:
       path: /etc/packetbeat/packetbeat.yml 
       insertafter: '  #password: "changeme"'
       block: |2
           ssl:
             enabled: true
             ca_trusted_fingerprint: "{{ ca_fingerprint_value }}"  
     
- name: Adding elastic user credentials password
  lineinfile:
      path: /etc/packetbeat/packetbeat.yml 
      regex: '  #password: "changeme"'
      line: "  password: ${ES_PW}"
 
- name: restart packetbeat
  shell: systemctl restart packetbeat.service
    

    
