---
# tasks file for deploy_ELK
- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Check if a reboot is needed for Debian and Ubuntu boxes
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no
- name: Reboot the Debian or Ubuntu server
  reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
  when: reboot_required_file.stat.exists
- name: Import GPG key
  shell: |
       wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
       apt-get install apt-transport-https
- name: Add Elasticsearch repository
  shell: |
        echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list
- name: Update package cache
  apt:
     update_cache: yes

- name: Install ELK stack
  apt:
       name: "{{ item }}"
       state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  loop: "{{ ELK }}"
- name: Installing NGINX Webserver
  apt:
      name: nginx
      state: latest
