---
- name: Deploying { Single-node } ELK with { beats }
  hosts: ubuntu
  become: True
  vars_prompt:
  - name: port80
    prompt: Did you open Port 80? it is mandatory to open port 80 for letsencrypt challenges
    private: false
  - name: ddns_name
    prompt: Enter your ddns domain without .duckdns.org
    private: false
  roles:
    - role_deploy_ELK
    - role_deploy_beats
    - role_deploy_reverse_proxy-NGINX_DDNS
- name: Enabling 30 days-trial for more unlimited access to premium content during 30-days
  import_playbook: enable_30days_trial.yml

