---
- name: Deploying { Single-node } ELK with { beats }
  hosts: ubuntu
  become: t
  roles:
    - role_deploy_ELK
    - role_deploy_beats
- name: Enabling 30 days-trial for more unlimited access to premium content during 30-days
  import_playbook: enable_30days_trial.yml

