---
- name: enabling 30 days trial
  hosts: ubuntu
  gather_facts: n
  become: t
  vars_files:
     - locked_cred
  tasks:
  - shell: |
#curl -k -X POST "https://localhost:9200/_license/start_trial?acknowledge=true" -u  "{{ elastic_user }}":"{{ elastic_pw }}"
       curl -k -X POST "https://localhost:9200/_license/start_trial?acknowledge=true" -u elastic:"{{ elastic_pw_val.content | b64decode }}"
    register: res
  - debug: 
       msg: "{{ res.stdout_lines }}"
