---
- name: Tuning elasticsearch for better index searching
  hosts: ubuntu
  become: true
  gather_facts: false
  tasks:
    - name: Disable swapping
      ansible.builtin.shell: |
         swapoff -a

    - name: Virtual memory
      ansible.builtin.shell: echo "vm.max_map_count=262144" >> /etc/sysctl.conf

    - name: net.ipv4.tcp_retries2
      ansible.builtin.shell: echo "net.ipv4.tcp_retries2=5" >> /etc/sysctl.conf

    - name: Configure swappiness
      ansible.builtin.shell: |
          echo "vm.swappiness=1" >> /etc/sysctl.conf
          sudo sysctl -p

    - name: Enable bootstrap.memory_lock
      ansible.builtin.lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regex: "^#bootstrap.memory_lock:"
        line: "bootstrap.memory_lock: true"

    - name: Restart elasticsearch
      ansible.builtin.shell: systemctl restart elasticsearch

    - name: Set ulimit -l unlimited
      ansible.builtin.blockinfile:
        path: /etc/security/limits.conf
        block: |
          # allow user 'elasticsearch' mlockall
          elasticsearch soft memlock unlimited
          elasticsearch hard memlock unlimited

    - name: Set number of replicas to 0
      ansible.builtin.debug:
        msg: "Make an API call for the replicas"

- name: Setting up number_of_replicas to 0 via API call
  hosts: localhost
  tasks:
    - name: Make API call to set number of replicas to 0
      ansible.builtin.shell: >
        curl -k -H "Content-Type: application/json" -XPUT https://localhost:9200/_settings -d '{ "index" : { "number_of_replicas" : 0 } }' -u elastic:"{{ elastic_pw_val.content | b64decode }}"
      register: curl_res

    - name: Printing results
      ansible.builtin.debug:
        var: curl_res.stdout_lines
