---
# This playbook is dedicated to tune at maximum the single-node deployment
# Official documentation for the tuning https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html
- name: Tuning elasticsearch for a better index searching
  hosts: ubuntu
  become: t
  gather_facts: f
  tasks:
  - name: Disable swapping
#To check of the swap memory is enable use these commands 
#swapon --show
#cat /proc/swaps
#lsblk
#free -h
     shell: |
       ss
       swapoff -a
  - name: Virtual memory
    shell: echo "vm.max_map_count=262144" >> /etc/sysctl.conf
  - name: net.ipv4.tcp_retries2
    shell: echo "net.ipv4.tcp_retries2=5" >> /etc/sysctl.conf
  - name: Configure swapiness
    shell: |
        echo "vm.swappiness=1" >> /etc/sysctl.conf
        sudo sysctl -p    
  - name: Enable bootstrap.memory_lock
    lineinfile:
       path: /etc/elasticsearch/elasticsearch.yml
       regex: "^#bootstrap.memory_lock:"
       line: "bootstrap.memory_lock: true"
  - name: restart elasticsearch
    shell: systemctl restart elasticsearch.yml
  - name: set ulimit -l unlimited
    blockinfile:
      path: /etc/security/limits.conf
      block: |
        # allow user 'elasticsearch' mlockall
         elasticsearch soft memlock unlimited
         elasticsearch hard memlock unlimited
  - name: Set number of replicas to 0, if in a multinode cluster you should do that for the health check
    debug: 
      msg: "Make an API call for the replicas"
# Configurations needed for single-node deployment
#
#
#
- name: Setting up number_of_replicas to 0 via API call
  shell: |
       curl -k -H "Content-Type: application/json" -XPUT https://localhost:9200/*/_settings -d '{ "index" : { "number_of_replicas" : 0 } }' -u elastic:"{{ elastic_pw_val.content | b64decode }}"
  register: curl_res
- name: Printing results
  debug:
     var: curl_res.stdout_lines
