---
# handlers file for deploy_ELK
- name: restart_kibana
  service:
    name: kibana
    state: restarted
    enabled: yes
- name: restart_elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
